# -*- coding: utf-8 -*-
"""Transformações numéricas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PTw0I_2h2IaZdrBcmP_fk7wIEy8EwoeK

# Transformações numéricas uteis:

- Binário para Inteiros
- Inteiros para Binários
"""

# Numeros binários para inteiros

nBinario = int(input(f"Digite o valor binário: "))
n= len(str(nBinario)) # Contando o numero de caracteres em str.
decimal = 0
i = 0

while n >= 0:
  resto = nBinario % 10
  decimal += resto*(2**i)
  n -= 1
  i += 1
  nBinario = nBinario // 10

print(f"Valor binário {nBinario} - Seu valor em decimal {decimal} ")

# Inteiros para binários

nInteiro = int(input(f"Digite o valor inteiro: "))

numero_digitado = nInteiro
quociente = 1
lista = []

while quociente >=1:
  resto = nInteiro % 2
  lista.insert(0,resto)
  quociente = nInteiro // 2
  nInteiro = quociente

binario = ''.join([str(item) for item in lista])
print(numero_digitado, binario, sep=" - ")


def inteiroBinario(nInt):
  return bin(nInt)

print(inteiroBinario(nInteiro))




#print(ord(b))

# for c in nInteiro:
#   v = ord(c)
#   print(c,v,f'{v:b}', sep="\t")